apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      serviceAccountName: data-sa
      initContainers:              # <-- here, sibling to containers
        - name: awscli-init
          image: amazon/aws-cli
          command:
            - sh
            - -c
            - |
              echo "Validating MinIO access..."
              aws --endpoint-url http://minio.minio.svc.cluster.local:9000 s3 ls || exit 1
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-creds
                  key: accesskey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-creds
                  key: secretkey
      containers:
        - name: data-service
          image: hashicorp/http-echo
          args:
            - "-text=hello"
          ports:
            - containerPort: 5678
          livenessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 2
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"

