apiVersion: v1
kind: Pod
metadata:
  name: stress-test
  namespace: default
spec:
  containers:
    - name: stress
      image: alpine:latest
      command: ["sh", "-c"]
      args:
        - apk add --no-cache stress && stress --cpu 2 --vm 1 --vm-bytes 64M --timeout 60s
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"

