apiVersion: v1
kind: Pod
metadata:
  name: auth-test-pod
  namespace: application
spec:
  serviceAccountName: auth-sa   # same SA as auth-service
  containers:
    - name: awscli
      image: amazon/aws-cli
      command: ["sh", "-c", "aws --endpoint-url http://minio.minio.svc.cluster.local:9000 s3 ls"]
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: accesskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: secretkey
  restartPolicy: Never

