apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-minio-access-to-auth-sa
spec:
  validationFailureAction: enforce
  rules:
    - name: block-auth-sa-access-to-minio
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "auth-sa is not allowed to access MinIO"
        deny:
          conditions:
            - key: "{{ request.object.spec.serviceAccountName }}"
              operator: Equals
              value: auth-sa

